# Generated by Django 5.0.6 on 2024-10-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todos",
            fields=[
                ("sno", models.AutoField(primary_key=True, serialize=False)),
                ("desc", models.TextField()),
                ("status", models.BooleanField(default=False)),
                ("time_created", models.DateTimeField(auto_now=True)),
                ("time_updated", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
